// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// NOTE: Added fallback values to prevent "supabaseUrl is required" errors
// in preview/build scenarios where env vars may not be injected properly.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://iocfocbvdkggiigfknbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvY2ZvY2J2ZGtnZ2lpZ2ZrbmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTI5MTIsImV4cCI6MjA4NTYyODkxMn0.WaB8Jwr-9KllanoAE7cqECzMjVndAelzQge_idcDFIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});